from pptx import Presentation as new_presentation

from core.game_metadata import Card

import card_ordering
import caching
from utils import pptx_funcs

IMAGE_PATH = r"C:\Users\Zachary\Coding\GitHub\DraftMetaReporter\Notebooks\temp.jpeg"


def gen_powerpoint_half(card_names: list[str], file_name: str):
    prs = new_presentation()

    for card_name in card_names:
        height, width = caching.download_card_image(card_name)
        pptx_funcs.add_centered_image_slide(prs, IMAGE_PATH)

    prs.save(file_name)


def gen_set_review_pptx(set_code: str, split_point: int):
    caching.populate_cache([set_code])
    cards = card_ordering.get_set_order(set_code)

    commons_and_uncommons = cards[0:split_point]
    rares_and_mythic = cards[split_point:]

    gen_powerpoint_half(commons_and_uncommons,  f"{set_code} - Commons and Uncommons.pptx")
    gen_powerpoint_half(rares_and_mythic,  f"{set_code} - Rares and Mythics .pptx")


def gen_by_set():
    SPLIT = 18

    gen_set_review_pptx(SET, SPLIT)


def gen_by_card_lists():
    caching.populate_cache({SET, "SPG"})

    day_one_keys = [
        ("MKM", 221, "No More Lies"),
        ("MKM", 223, "Private Eye"),
        ("MKM", 232, "Soul Search"),
        ("MKM", 243, "Wispdrinker Vampire"),
        ("MKM", 218, "Lightning Helix"),
        ("MKM", 219, "Meddling Youths"),
        ("MKM", 233, "Sumala Sentry"),
        ("MKM", 191, "Buried in the Garden"),
        ("MKM", 194, "Curious Cadaver"),
        ("MKM", 192, "Coerced to Kill"),
        ("MKM", 205, "Gleaming Geardrake"),
        ("MKM", 196, "Detective's Satchel"),
        ("MKM", 201, "Evidence Examiner"),
        ("MKM", 227, "Repulsive Mutation"),
        ("MKM", 229, "Rune-Brand Juggler"),
        ("MKM", 195, "Deadly Complication"),
        ("MKM", 208, "Insidious Roots"),
        ("MKM", 213, "Kraul Whipcracker"),
        ("MKM", 190, "Break Out"),
        ("MKM", 235, "Tin Street Gossip"),
        ("MKM", 248, "Fuss // Bother"),
        ("MKM", 250, "Push // Pull"),
        ("MKM", 246, "Cease // Desist"),
        ("MKM", 247, "Flotsam // Jetsam"),
        ("MKM", 249, "Hustle // Bustle"),
        ("MKM", 206, "Granite Witness"),
        ("MKM", 230, "Sanguine Savior"),
        ("MKM", 197, "Dog Walker"),
        ("MKM", 193, "Crowd-Control Warden"),
        ("MKM", 203, "Faerie Snoop"),
        ("MKM", 204, "Gadget Technician"),
        ("MKM", 239, "Undercover Crocodelf"),
        ("MKM", 231, "Shady Informant"),
        ("MKM", 225, "Rakish Scoundrel"),
        ("MKM", 228, "Riftburst Hellion"),
        ("MKM", 29, "Novice Inspector"),
        ("MKM", 24, "Marketwatch Phantom"),
        ("MKM", 33, "Seasoned Consultant"),
        ("MKM", 5, "Auspicious Arrival"),
        ("MKM", 14, "Due Diligence"),
        ("MKM", 19, "Inside Source"),
        ("MKM", 22, "Make Your Move"),
        ("MKM", 23, "Makeshift Binding"),
        ("MKM", 17, "Griffnaut Tracker"),
        ("MKM", 25, "Museum Nightwatch"),
        ("MKM", 30, "On the Job"),
        ("MKM", 18, "Haazda Vigilante"),
        ("MKM", 11, "Defenestrated Phantom"),
        ("MKM", 16, "Forum Familiar"),
        ("MKM", 21, "Krovod Haunch"),
        ("MKM", 37, "Wrench"),
        ("MKM", 26, "Neighborhood Guardian"),
        ("MKM", 28, "Not on My Watch"),
        ("MKM", 31, "Perimeter Enforcer"),
        ("MKM", 32, "Sanctuary Wall"),
        ("MKM", 6, "Call a Surprise Witness"),
        ("MKM", 8, "Case of the Gateway Express"),
        ("MKM", 9, "Case of the Pilfered Proof"),
        ("MKM", 7, "Case File Auditor"),
        ("MKM", 20, "Karlov Watchdog"),
        ("MKM", 15, "Essence of Antiquity"),
        ("MKM", 2, "Absolving Lammasu"),
        ("MKM", 39, "Behind the Mask"),
        ("MKM", 41, "Bubble Smuggler"),
        ("MKM", 52, "Deduce"),
        ("MKM", 62, "Jaded Analyst"),
        ("MKM", 69, "Reasonable Doubt"),
        ("MKM", 74, "Unauthorized Exit"),
        ("MKM", 49, "Crimestopper Sprite"),
        ("MKM", 53, "Dramatic Accusation"),
        ("MKM", 68, "Projektor Inspector"),
        ("MKM", 46, "Cold Case Cracker"),
        ("MKM", 66, "Out Cold"),
        ("MKM", 40, "Benthic Criminologists"),
        ("MKM", 60, "Hotshot Investigators"),
        ("MKM", 43, "Candlestick"),
        ("MKM", 44, "Case of the Filched Falcon"),
        ("MKM", 51, "Curious Inquiry"),
        ("MKM", 65, "Mistway Spy"),
        ("MKM", 42, "Burden of Proof"),
        ("MKM", 54, "Eliminate the Impossible"),
        ("MKM", 55, "Exit Specialist"),
        ("MKM", 56, "Fae Flight"),
        ("MKM", 58, "Forensic Researcher"),
        ("MKM", 59, "Furtive Courier"),
        ("MKM", 72, "Sudden Setback"),
        ("MKM", 73, "Surveillance Monitor"),
        ("MKM", 63, "Living Conundrum"),
        ("MKM", 38, "Agency Outfitter"),
        ("MKM", 103, "Slice from the Shadows"),
        ("MKM", 105, "Snarling Gorehound"),
        ("MKM", 107, "Toxin Analysis"),
        ("MKM", 101, "Repeat Offender"),
        ("MKM", 109, "Unscrupulous Agent"),
        ("MKM", 84, "Extract a Confession"),
        ("MKM", 76, "Alley Assailant"),
        ("MKM", 81, "Cerebral Confiscation"),
        ("MKM", 95, "Murder"),
        ("MKM", 102, "Rot Farm Mortipede"),
        ("MKM", 93, "Macabre Reconstruction"),
        ("MKM", 75, "Agency Coroner"),
        ("MKM", 78, "Basilica Stalker"),
        ("MKM", 79, "Case of the Gorgon's Kiss"),
        ("MKM", 85, "Festerleech"),
        ("MKM", 90, "Lead Pipe"),
        ("MKM", 100, "Presumed Dead"),
        ("MKM", 91, "Leering Onlooker"),
        ("MKM", 92, "Long Goodbye"),
        ("MKM", 82, "Clandestine Meddler"),
        ("MKM", 104, "Slimy Dualleech"),
        ("MKM", 106, "Soul Enervation"),
        ("MKM", 96, "Nightdrinker Moroii"),
        ("MKM", 108, "Undercity Eliminator"),
        ("MKM", 89, "It Doesn't Add Up"),
        ("MKM", 99, "Polygraph Orb"),
        ("MKM", 98, "Persuasive Interrogators"),
        ("MKM", 125, "Felonious Rage"),
        ("MKM", 130, "Goblin Maskmaker"),
        ("MKM", 144, "Shock"),
        ("MKM", 122, "Demand Answers"),
        ("MKM", 128, "Galvanize"),
        ("MKM", 133, "Innocent Bystander"),
        ("MKM", 142, "Red Herring"),
        ("MKM", 116, "The Chase Is On"),
        ("MKM", 129, "Gearbane Orangutan"),
        ("MKM", 139, "Person of Interest"),
        ("MKM", 138, "Offender at Large"),
        ("MKM", 143, "Rubblebelt Braggart"),
        ("MKM", 145, "Suspicious Detonation"),
        ("MKM", 119, "Convenient Target"),
        ("MKM", 126, "Frantic Scapegoat"),
        ("MKM", 134, "Knife"),
        ("MKM", 146, "Torch the Witness"),
        ("MKM", 117, "Concealed Weapon"),
        ("MKM", 124, "Expose the Culprit"),
        ("MKM", 141, "Reckless Detective"),
        ("MKM", 147, "Vengeful Tracker"),
        ("MKM", 113, "Case of the Burning Masks"),
        ("MKM", 121, "Crime Novelist"),
        ("MKM", 131, "Harried Dronesmith"),
        ("MKM", 115, "Caught Red-Handed"),
        ("MKM", 120, "Cornered Crook"),
        ("MKM", 112, "Bolrac-Clan Basher"),
        ("MKM", 170, "Pick Your Poison"),
        ("MKM", 174, "Rubblebelt Maverick"),
        ("MKM", 159, "Fanatical Strength"),
        ("MKM", 169, "Nervous Gardener"),
        ("MKM", 180, "Tunnel Tipster"),
        ("MKM", 183, "Vitu-Ghazi Inspector"),
        ("MKM", 149, "Airtight Alibi"),
        ("MKM", 177, "Slime Against Humanity"),
        ("MKM", 178, "They Went This Way"),
        ("MKM", 154, "Bite Down on Crime"),
        ("MKM", 168, "Loxodon Eavesdropper"),
        ("MKM", 182, "Vengeful Creeper"),
        ("MKM", 179, "Topiary Panther"),
        ("MKM", 161, "Get a Leg Up"),
        ("MKM", 164, "Hard-Hitting Question"),
        ("MKM", 165, "Hedge Whisperer"),
        ("MKM", 173, "Rope"),
        ("MKM", 148, "Aftermath Analyst"),
        ("MKM", 160, "Flourishing Bloom-Kin"),
        ("MKM", 156, "Case of the Trampled Garden"),
        ("MKM", 171, "Pompous Gadabout"),
        ("MKM", 175, "Sample Collector"),
        ("MKM", 157, "Chalk Outline"),
        ("MKM", 163, "Greenbelt Radical"),
        ("MKM", 158, "Culvert Ambusher"),
        ("MKM", 167, "A Killer Among Us"),
        ("MKM", 162, "Glint Weaver"),
        ("MKM", 257, "Thinking Cap"),
        ("MKM", 252, "Gravestone Strider"),
        ("MKM", 256, "Sanitation Automaton"),
        ("MKM", 255, "Magnifying Glass"),
        ("MKM", 1, "Case of the Shattered Pact"),
        ("MKM", 253, "Lumbering Laundry"),
        ("MKM", 254, "Magnetic Snuffler"),
        ("MKM", 261, "Escape Tunnel"),
        ("MKM", 265, "Public Thoroughfare"),
        ("MKM", 258, "Branch of Vitu-Ghazi"),
        ("MKM", 267, "Scene of the Crime"),
    ]
    day_two_keys = [
        ("MKM", 222, "Officious Interrogation"),
        ("MKM", 185, "Alquist Proft, Master Sleuth"),
        ("MKM", 202, "Ezrim, Agency Chief"),
        ("MKM", 234, "Teysa, Opulent Oligarch"),
        ("MKM", 237, "Treacherous Greed"),
        ("MKM", 211, "Kaya, Spirits' Justice"),
        ("MKM", 242, "Warleader's Call"),
        ("MKM", 184, "Agrus Kos, Spirit of Justice"),
        ("MKM", 188, "Aurelia, the Law Above"),
        ("MKM", 238, "Trostani, Three Whispers"),
        ("MKM", 236, "Tolsimir, Midnight's Light"),
        ("MKM", 226, "Relive the Past"),
        ("MKM", 199, "Drag the Canal"),
        ("MKM", 216, "Lazav, Wearer of Faces"),
        ("MKM", 200, "Etrata, Deadly Fugitive"),
        ("MKM", 215, "Kylox's Voltstrider"),
        ("MKM", 207, "Ill-Timed Explosion"),
        ("MKM", 214, "Kylox, Visionary Inventor"),
        ("MKM", 198, "Doppelgang"),
        ("MKM", 212, "Kellan, Inquisitive Prodigy"),
        ("MKM", 241, "Vannifar, Evolved Enigma"),
        ("MKM", 189, "Blood Spatter Analysis"),
        ("MKM", 210, "Judith, Carnage Connoisseur"),
        ("MKM", 224, "Rakdos, Patron of Chaos"),
        ("MKM", 187, "Assassin's Trophy"),
        ("MKM", 240, "Urgent Necropsy"),
        ("MKM", 209, "Izoni, Center of the Web"),
        ("MKM", 244, "Worldsoul's Rage"),
        ("MKM", 245, "Yarus, Roar of the Old Gods"),
        ("MKM", 186, "Anzrag, the Quake-Mole"),
        ("MKM", 217, "Leyline of the Guildpact"),
        ("MKM", 220, "Niv-Mizzet, Guildpact"),
        ("MKM", 10, "Case of the Uneaten Feast"),
        ("MKM", 13, "Doorkeeper Thrull"),
        ("MKM", 3, "Assemble the Players"),
        ("MKM", 34, "Tenth District Hero"),
        ("MKM", 35, "Unyielding Gatekeeper"),
        ("MKM", 36, "Wojek Investigator"),
        ("MKM", 12, "Delney, Streetwise Lookout"),
        ("MKM", 27, "No Witnesses"),
        ("MKM", 4, "Aurelia's Vindicator"),
        ("MKM", 64, "Lost in the Maze"),
        ("MKM", 67, "Proft's Eidetic Memory"),
        ("MKM", 45, "Case of the Ransacked Lab"),
        ("MKM", 48, "Coveted Falcon"),
        ("MKM", 50, "Cryptic Coat"),
        ("MKM", 57, "Forensic Gadgeteer"),
        ("MKM", 71, "Steamcore Scholar"),
        ("MKM", 70, "Reenact the Crime"),
        ("MKM", 61, "Intrude on the Mind"),
        ("MKM", 47, "Conspiracy Unraveler"),
        ("MKM", 80, "Case of the Stashed Skeleton"),
        ("MKM", 86, "Homicide Investigator"),
        ("MKM", 97, "Outrageous Robbery"),
        ("MKM", 87, "Hunted Bonebrute"),
        ("MKM", 77, "Barbed Servitor"),
        ("MKM", 88, "Illicit Masquerade"),
        ("MKM", 94, "Massacre Girl, Known Killer"),
        ("MKM", 83, "Deadly Cover-Up"),
        ("MKM", 110, "Vein Ripper"),
        ("MKM", 118, "Connecting the Dots"),
        ("MKM", 127, "Fugitive Codebreaker"),
        ("MKM", 140, "Pyrotechnic Performer"),
        ("MKM", 123, "Expedited Inheritance"),
        ("MKM", 114, "Case of the Crimson Pulse"),
        ("MKM", 135, "Krenko, Baron of Tin Street"),
        ("MKM", 137, "Lamplight Phoenix"),
        ("MKM", 136, "Krenko's Buzzcrusher"),
        ("MKM", 111, "Anzrag's Rampage"),
        ("MKM", 132, "Incinerator of the Guilty"),
        ("MKM", 150, "Analyze the Pollen"),
        ("MKM", 176, "Sharp-Eyed Rookie"),
        ("MKM", 151, "Archdruid's Charm"),
        ("MKM", 152, "Audience with Trostani"),
        ("MKM", 181, "Undergrowth Recon"),
        ("MKM", 153, "Axebane Ferox"),
        ("MKM", 155, "Case of the Locked Hothouse"),
        ("MKM", 166, "Hide in Plain Sight"),
        ("MKM", 172, "The Pride of Hull Clade"),
        ("MKM", 251, "Cryptex"),
        ("MKM", 259, "Commercial District"),
        ("MKM", 260, "Elegant Parlor"),
        ("MKM", 262, "Hedge Maze"),
        ("MKM", 263, "Lush Portico"),
        ("MKM", 264, "Meticulous Archive"),
        ("MKM", 266, "Raucous Theater"),
        ("MKM", 268, "Shadowy Backstreet"),
        ("MKM", 269, "Thundering Falls"),
        ("MKM", 270, "Undercity Sewers"),
        ("MKM", 271, "Underground Mortuary"),
        ("APC", 117, "Putrid Warrior"),
        ("DKA", 4, "Burden of Guilt"),
        ("MH2", 46, "Hard Evidence"),
        ("SOM", 96, "Kuldotha Rebirth"),
        ("ISD", 183, "Gnaw to the Bone"),
        ("ONS", 272, "Krosan Tusker"),
        ("SOI", 262, "Shard of Broken Glass"),
        ("KLD", 221, "Metalspinner's Puzzleknot"),
        ("RNA", 182, "High Alert"),
        ("STX", 220, "Quintorius, Field Historian"),
        ("ARB", 68, "Enlisted Wurm"),
        ("HOU", 149, "Consign // Oblivion"),
        ("DDU", 50, "Maverick Thopterist"),
        ("MH2", 191, "Combine Chrysalis"),
        ("DKA", 143, "Stromkirk Captain"),
        ("JOU", 153, "Nyx Weaver"),
        ("C16", 47, "Treacherous Terrain"),
        ("MBS", 10, "Leonin Relic-Warder"),
        ("2X2", 17, "Mentor of the Meek"),
        ("DIS", 33, "Spell Snare"),
        ("CLB", 85, "Mystery Key"),
        ("ELD", 107, "Syr Konrad, the Grim"),
        ("XLN", 91, "Bishop of the Bloodstained"),
        ("DOM", 130, "Goblin Warchief"),
        ("UMA", 138, "Magmaw"),
        ("VOW", 207, "Laid to Rest"),
        ("M14", 213, "Millstone"),
        ("DIS", 173, "Ghost Quarter"),
        ("RAV", 277, "Duskmantle, House of Shadow"),
        ("UMA", 247, "Mistveil Plains"),
        ("C21", 19, "Monologue Tax"),
        ("MH1", 21, "Ranger-Captain of Eos"),
        ("WAR", 54, "Jace, Wielder of Mysteries"),
        ("ONS", 89, "Ixidor, Reality Sculptor"),
        ("MRD", 99, "Mass Hysteria"),
        ("SOM", 98, "Molten Psyche"),
        ("DGM", 34, "Possibility Storm"),
        ("ORI", 176, "Evolutionary Leap"),
        ("RTR", 140, "Worldspine Wurm"),
        ("KLD", 235, "Smuggler's Copter"),
        ("SPG", 27, "Drown in the Loch"),
        ("SPG", 19, "Ghostly Prison"),
        ("SPG", 20, "Fabricate"),
        ("SPG", 21, "Show and Tell"),
        ("SPG", 22, "Tragic Slip"),
        ("SPG", 23, "Victimize"),
        ("SPG", 24, "Gamble"),
        ("SPG", 26, "Tireless Tracker"),
        ("SPG", 25, "Crashing Footfalls"),
        ("SPG", 28, "Field of the Dead"),
    ]

    day_one_cards = [caching.get_card_data_by_set(s, n, name)["name"] for s, n, name in day_one_keys]
    day_two_cards = [caching.get_card_data_by_set(s, n, name)["name"] for s, n, name in day_two_keys]

    gen_powerpoint_half(day_one_cards,  f"{SET} - Commons and Uncommons.pptx")
    gen_powerpoint_half(day_two_cards,  f"{SET} - Rares and Mythics.pptx")


if __name__ == "__main__":
    SET = "MKM"

    gen_by_card_lists()

