# 17 Lands URL Bases
BASE_17L_URL = 'https://www.17lands.com'
COLOR_17L_URL = f'{BASE_17L_URL}/data/colors'
EXPANSIONS_17L_URL = f'{BASE_17L_URL}/data/expansions'
FORMATS_17L_URL = f'{BASE_17L_URL}/data/formats'
PLAY_DRAW_17L_URL = f'{BASE_17L_URL}/data/play_draw'
COLOR_RATING_17L_URL = f'{BASE_17L_URL}/color_ratings/data'
CARD_RATING_17L_URL = f'{BASE_17L_URL}/card_ratings/data'
CARD_EVAL_17L_URL = f'{BASE_17L_URL}/card_evaluation_metagame/data'
TROPHY_17L_URL = f'{BASE_17L_URL}/data/trophies'
DRAFT_LOG_17L_URL = f'{BASE_17L_URL}/data/draft/stream'
DECK_17L_URL = f'{BASE_17L_URL}/data/deck'
DETAILS_17L_URL = f'{BASE_17L_URL}/data/details'
TIER_17L_URL = f'{BASE_17L_URL}/card_tiers/data'
